# from https://github.com/rootpy/rootpy/blob/master/.travis.yml
# travis-ci.org build & test configuration
language: python

python:
  - "2.7"
#  - "3.2"

env:
  - ROOT=5.34.05
# - ROOT=5.27.06

install:
  # Check if we are running Python 2 or 3. This is needed for the apt-get package names
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then export PYTHON_SUFFIX="3"; fi

  # # This is needed for the docs
  # - git submodule init
  # - git submodule update

  # Use system python, not virtualenv, because building the dependencies from source takes too long
  - deactivate # the virtualenv

  # Needed because sometimes travis' repositories get out of date
  - time sudo apt-get update -qq

  # Install the dependencies we need
  # - time sudo apt-get install -qq python${PYTHON_SUFFIX}-numpy python${PYTHON_SUFFIX}-sphinx python${PYTHON_SUFFIX}-nose
  - time sudo apt-get install -qq python${PYTHON_SUFFIX}-numpy
  - time sudo apt-get install -qq python${PYTHON_SUFFIX}-scipy
  # # matplotlib and PyTables are not available for Python 3 as packages from the main repo yet.
  # - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then time sudo apt-get install -qq python${PYTHON_SUFFIX}-matplotlib python${PYTHON_SUFFIX}-tables; fi

  # Install a ROOT binary that we custom-built in a 64-bit Ubuntu VM
  # for the correct Python / ROOT version
  - time wget --no-check-certificate https://dl.dropbox.com/u/4923986/rootpy/64/root_v${ROOT}_Python_${TRAVIS_PYTHON_VERSION}.tar.gz
  - time tar zxf root_v${ROOT}_Python_${TRAVIS_PYTHON_VERSION}.tar.gz
  - source root_v${ROOT}_Python_${TRAVIS_PYTHON_VERSION}/bin/thisroot.sh

  # adjust environment
  - cd ..
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - export PATH=$PATH:`pwd`/supy/bin

  # add a configuration
  - ln -s supy/defaults.py configuration.py

script:

  # Check if root and PyROOT work ok
  - time root -l -q
  - time python -c 'import ROOT; ROOT.TBrowser()'

  tar xzf data/SusyNt_dependencies.tgz
  ls
  echo "pwd is now `pwd`"

  # setup RootCore
  cd RootCore
  echo "pwd is now `pwd`"
  ./configure
  source scripts/setup.sh
  cd ..

  # compile
  ./RootCore/scripts/compile.sh

  # Now run the tests
  #
  echo "Running the tests"

