# from https://github.com/rootpy/rootpy/blob/master/.travis.yml
# travis-ci.org build & test configuration
language: python

python:
  - "2.7"
#  - "3.2"

env:
# - ROOT=5.27.06
# - ROOT=5.34.05
  - ROOT=5-34-08

install:
  # Check if we are running Python 2 or 3. This is needed for the apt-get package names
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then export PYTHON_SUFFIX="3"; fi

  # # This is needed for the docs
  # - git submodule init
  # - git submodule update

  # Use system python, not virtualenv, because building the dependencies from source takes too long
  - deactivate # the virtualenv

  # Needed because sometimes travis' repositories get out of date
  - time sudo apt-get update -qq

  # Install the dependencies we need
  # - time sudo apt-get install -qq python${PYTHON_SUFFIX}-numpy python${PYTHON_SUFFIX}-sphinx python${PYTHON_SUFFIX}-nose
  - time sudo apt-get install -qq python${PYTHON_SUFFIX}-numpy
  - time sudo apt-get install -qq python${PYTHON_SUFFIX}-scipy
  # # matplotlib and PyTables are not available for Python 3 as packages from the main repo yet.
  # - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then time sudo apt-get install -qq python${PYTHON_SUFFIX}-matplotlib python${PYTHON_SUFFIX}-tables; fi

  # Install a ROOT binary that we custom-built in a 64-bit Ubuntu VM
  # for the correct Python / ROOT version
  - time wget --tries=2 --no-check-certificate https://copy.com/rtIyUdxgjt7h/ci/root_builds/root_v${ROOT}_python_${TRAVIS_PYTHON_VERSION}.tar.gz
  - time tar zxf root_v${ROOT}_python_${TRAVIS_PYTHON_VERSION}.tar.gz
  - mv root_v${ROOT}_python_${TRAVIS_PYTHON_VERSION} root
  - source root/bin/thisroot.sh
  # just to debug and see what root features are available
  - root-config --config

  # get dependencies
  - cd ..
  - tar xzf SusyNtuple/data/SusyNt_dependencies.tgz
  - cd -

  # setup RootCore
  - cd ../RootCore
  - echo "pwd is now `pwd`"
  - ./configure
  - cd ..
  - source RootCore/scripts/setup.sh
  - ./RootCore/scripts/find_packages.sh
  - ./RootCore/scripts/compile.sh
  - cd SusyNtuple/run

script:
  # Check if root and PyROOT work ok
  - time root -l -b -q
  - time python -c 'import ROOT; ROOT.TBrowser()'

  # Now run the tests
  - Susy2LepCF --help

